# Generated by Django 5.2.4 on 2025-07-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactmessage_alter_comment_body_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='old contact', max_length=200),
            preserve_default=False,
        ),
    ]
